version: 2

sources:
  - name: raw_data_circle
    description: raw data circle sportswear from le wagon
    tables:
      - name: raw_cc_funnel
        description: stock of products
      - name: raw_cc_funnel_priority
        description: sales of products

models:
  - name: stg_cc_funnel
    columns:
      - name: company
        tests:
          - unique
          - not_null
      - name: priority
        tests:
          - accepted_values:
              values: ['Low', 'Medium', 'High']
  
  - name: stg_cc_funnel
    columns:
      - name: company
        tests:
          - unique
          - not_null
      - name: date_lead
        tests:
          - not_null